### ISSUE TITLE
Unable to run gradient on ExDoc

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#78] opened 2022-05-21 12:34 UTC
This is my branch based on ExDoc main, which only adds Gradient as a dependency:
https://github.com/eksperimental/ex_doc/tree/gradient

after `mix do clean + deps.get`
I run `mix gradient` and I get.

```
$ mix gradient
Loading deps...
Compiling project...
Typechecking files...
lib/ex_doc/autolink.ex: ** (ArgumentError) argument error
    :erlang.++([[[[[[[[[[[[[[[] | "\e[36m"], "("], "["], "]"], ","], " "], "nonempty_list"], "("], ")"], " ->"], " "], "false"], ")"] | "\e[0m"], [])
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/ex_doc/deps/gradualizer/src/gradualizer_fmt.erl:505: :gradualizer_fmt.pp_intersection_type/2
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/ex_doc/deps/gradualizer/src/gradualizer_fmt.erl:505: :gradualizer_fmt.pp_intersection_type/2
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/ex_doc/deps/gradualizer/src/gradualizer_fmt.erl:174: :gradualizer_fmt.format_type_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:208: Gradient.ElixirFmt.format_type_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:58: Gradient.ElixirFmt.print_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:44: anonymous fn/3 in Gradient.ElixirFmt.print_errors/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
```

It looks like a Gradualizer issue, still reporting it here so you guys can elevate it accordingly if it is necessary.

**Comment by eksperimental** [comment] 2022-05-21 12:38
Same with Phoenix.

```
lib/phoenix/code_reloader/server.ex: ** (ArgumentError) argument error
    :erlang.++([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...], ...], "["], ""], "{"], ":atom"], ","], " "], "0"], ","], " "], ":is_subtype"], "}"], ","], " "], "["], ""], "{"], ":var"], ","], " "], "0"], ","], " "], ":MonitorRef"], "}"], ","], " "], "{"], ":type"], ","], " "], "0"], ","], " "], ":reference"], ","], " "], "["], "]"], "}"], ""], "]"], ""], "]"], "}"], "\n"], "]"], ""], ")"] | "\e[0m"], [])
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/phoenix/deps/gradualizer/src/gradualizer_fmt.erl:507: :gradualizer_fmt.pp_intersection_type/2
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/phoenix/deps/gradualizer/src/gradualizer_fmt.erl:507: :gradualizer_fmt.pp_intersection_type/2
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/user/git/phoenix/deps/gradualizer/src/gradualizer_fmt.erl:174: :gradualizer_fmt.format_type_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:208: Gradient.ElixirFmt.format_type_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:58: Gradient.ElixirFmt.print_error/2
    (gradient 0.1.0) lib/gradient/elixir_fmt.ex:44: anonymous fn/3 in Gradient.ElixirFmt.print_errors/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3

```

**Comment by erszcz** [comment] 2022-05-24 07:43
I'm not sure what's wrong yet, but we certainly should not crash. Thanks for the report!

**Comment by erszcz** [comment] 2022-05-24 15:03
Well, it turns out the TODO in Gradualizer is a false lead. The problem is that `IO.ANSI.format()` returns an improper list, which cannot be handled by `++`. #79 fixes that, but it crashes on another issue.

**Comment by eksperimental** [comment] 2022-05-30 04:06
I think this one can be closed

**Comment by erszcz** [comment] 2022-05-30 08:43
@eksperimental Indeed, closing now as #79 is in 👍  Thanks again!

**Closed by erszcz** 2022-05-30 08:43 UTC
Labels: bug
